# Generated by Django 5.0.4 on 2024-07-28 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_cours_departement_niveau_role_salle_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='fichier_pdf',
            field=models.FileField(default='cours_pdfs/default.pdf', upload_to='cours_pdfs/'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='site1.cours'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='site1.etudiant'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='filieres',
            field=models.ManyToManyField(related_name='cours', to='site1.filiere'),
        ),
        migrations.AlterField(
            model_name='coursprofesseur',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_professeurs', to='site1.cours'),
        ),
        migrations.AlterField(
            model_name='coursprofesseur',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_professeurs', to='site1.professeur'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='site1.cours'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='site1.professeur'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='site1.salle'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='site1.departement'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='site1.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='site1.niveau'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='site1.departement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='site1.cours'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='site1.etudiant'),
        ),
        migrations.AlterField(
            model_name='moyenneponderee',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_ponderees', to='site1.etudiant'),
        ),
        migrations.AlterField(
            model_name='moyenneponderee',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_ponderees', to='site1.filiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='site1.cours'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='site1.etudiant'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='site1.departement'),
        ),
    ]
