# Generated by Django 5.0.4 on 2024-07-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_actualite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
