# Generated by Django 5.0.4 on 2024-07-28 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0013_administrateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Traitée', 'Traitée')], default='En cours', max_length=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.etudiant')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.note')),
            ],
        ),
    ]
