# Generated by Django 5.0.4 on 2024-08-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0015_delete_role_delete_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='photo_profil',
            field=models.ImageField(default='photos_profil/default_administrateur.jpg', upload_to='photos_profil/'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='photo_profil',
            field=models.ImageField(default='photos_profil/default_etudiant.jpg', upload_to='photos_profil/'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='photo_profil',
            field=models.ImageField(default='photos_profil/default_professeur.jpg', upload_to='photos_profil/'),
        ),
    ]
