# Generated by Django 5.0.4 on 2024-08-01 14:48

from django.db import migrations, models

"""
class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0016_administrateur_photo_profil_etudiant_photo_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]

"""



from django.db import migrations, models
import uuid

def generate_unique_matricule(apps, schema_editor):
    Etudiant = apps.get_model('site1', 'Etudiant')
    Professeur = apps.get_model('site1', 'Professeur')
    Administrateur = apps.get_model('site1', 'Administrateur')

    for etudiant in Etudiant.objects.all():
        etudiant.matricule = str(uuid.uuid4())
        etudiant.save(update_fields=['matricule'])

    for professeur in Professeur.objects.all():
        professeur.matricule = str(uuid.uuid4())
        professeur.save(update_fields=['matricule'])

    for administrateur in Administrateur.objects.all():
        administrateur.matricule = str(uuid.uuid4())
        administrateur.save(update_fields=['matricule'])

class Migration(migrations.Migration):

    dependencies = [
        # Ajoutez ici les dépendances de votre application
        ('site1', '0016_administrateur_photo_profil_etudiant_photo_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='matricule',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_matricule),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matricule',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='matricule',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
