# Generated by Django 5.0.4 on 2024-08-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0017_administrateur_matricule_etudiant_matricule_and_more'),
        ('site1', '0018_alter_administrateur_matricule_and_more'),
    ]

    operations = [
    ]
