# Generated by Django 5.0.4 on 2024-08-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0020_administrateur_adresse_administrateur_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='absence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='site1.absence'),
        ),
    ]
