# Generated by Django 5.0.4 on 2024-08-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0022_alter_reclamation_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='site1.absence'),
        ),
    ]
