# Generated by Django 5.0.4 on 2024-08-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0024_remove_reclamation_absence_justifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justifier',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifier', to='site1.absence'),
        ),
        migrations.AlterField(
            model_name='justifier',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifier', to='site1.etudiant'),
        ),
    ]
