# Generated by Django 5.0.4 on 2024-08-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0025_alter_justifier_absence_alter_justifier_etudiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Justifier',
        ),
    ]
