# Generated by Django 5.0.4 on 2024-08-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0026_delete_justifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('date_justification', models.DateField(auto_now_add=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifier', to='site1.absence')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifier', to='site1.etudiant')),
            ],
        ),
    ]
