# Generated by Django 5.0.4 on 2024-08-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0030_alter_cours_filieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='justifier',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Traitée', 'Traitée')], default='En cours', max_length=10),
        ),
    ]
