# Generated by Django 5.0.4 on 2024-08-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0031_justifier_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justifier',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Traitée', 'Traitée'), ('Refusée', 'Refusée')], default='En cours', max_length=10),
        ),
    ]
