# Generated by Django 5.0.4 on 2024-08-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='etudiant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='site1.etudiant'),
        ),
    ]
